const HIDDEN = [
  'create:crushed_aluminum_ore',
  'geolosys:aluminum_ingot',
  'geolosys:aluminum_nugget',
  'immersiveengineering:ore_aluminum',
  'geolosys:aluminum_ingot',
  
  'create:copper_block',
  'immersiveengineering:storage_copper',
  'charcoal_pit:copper_block',
  'tconstruct:copper_block',
  'cavesandcliffs:copper_block',
  'cavesandcliffs:raw_copper_block',
  'immersiveengineering:dust_copper',
  'create:crushed_copper_ore',
  'create:copper_ingot',
  'immersiveengineering:ingot_copper',
  'charcoal_pit:copper_ingot',
  'tconstruct:copper_ingot',
  'cavesandcliffs:copper_ingot',
  'geolosys:copper_ingot',
  'immersiveengineering:nugget_copper',
  'create:copper_nugget',
  'tconstruct:copper_nugget',
  'geolosys:copper_nugget',
  'immersiveengineering:ore_copper',
  'create:copper_ore',
  'cavesandcliffs:copper_ore',
  'tconstruct:copper_ore',
  'charcoal_pit:copper_ore',
  'mekanism:copper_ore',
  'cavesandcliffs:deepslate_copper_ore',
  'cavesandcliffs:raw_copper',
  'create:copper_sheet',
  'createaddition:copper_wire',
  
  'createaddition:diamond_grit',
  
  'immersiveengineering:dust_gold',
  'appliedenergistics2:gold_dust',
  'create:crushed_gold_ore',
  'atum:gold_ore',
  'boss_tools:venus_gold_ore',
  'cavesandcliffs:raw_gold',
  'cavesandcliffs:raw_gold_block',
  'cavesandcliffs:deepslate_gold_ore',
  'minecraft:nether_gold_ore',
  'minecraft:gold_ore',
  'create:golden_sheet',
  
  'appliedenergistics2:iron_dust',
  'immersiveengineering:dust_iron',
  'create:crushed_iron_ore',
  'atum:iron_ore',
  'minecraft:iron_ore',
  'cavesandcliffs:deepslate_iron_ore',
  'boss_tools:moon_iron_ore',
  'boss_tools:mars_iron_ore',
  'boss_tools:mercury_iron_ore',
  'infernalexp:basalt_iron_ore',
  'cavesandcliffs:raw_iron',
  'cavesandcliffs:raw_iron_block',
  'create:iron_sheet',
  'boss_tools:iron_plate',
  'boss_tools:iron_stick',
  'createaddition:iron_rod',
  
  'immersiveengineering:storage_lead',
  'immersiveengineering:dust_lead',
  'create:crushed_lead_ore',
  'immersiveengineering:ingot_lead',
  'geolosys:lead_ingot',
  'immersiveengineering:nugget_lead',
  'geolosys:lead_nugget',
  'immersiveengineering:ore_lead',
  'mekanism:lead_ore',
  
  'create:crushed_nickel_ore',
  'geolosys:nickel_ingot',
  'geolosys:nickel_nugget',
  'immersiveengineering:ore_nickel',
  
  'create:crushed_osmium_ore',
  'mekanism:osmium_ore',
  
  'create:crushed_silver_ore',
  'geolosys:silver_ingot',
  'geolosys:silver_nugget',
  'immersiveengineering:ore_silver',
  
  'create:crushed_tin_ore',
  'geolosys:tin_ingot',
  'geolosys:tin_nugget',
  'mekanism:tin_ore',
  
  'immersiveengineering:dust_uranium',
  'create:crushed_uranium_ore',
  'immersiveengineering:ingot_uranium',
  'immersiveengineering:nugget_uranium',
  'immersiveengineering:ore_uranium',
  'mekanism:uranium_ore',
  
  'geolosys:zinc_ingot',
  'geolosys:zinc_nugget',
  'create:zinc_ore',
  
  'minecraft:nether_quartz_ore',
  
  'minecraft:ancient_debris',
  
  'immersiveengineering:ingot_steel',
  'boss_tools:steel_ingot',
  'immersiveengineering:nugget_steel',
  'boss_tools:steel_nugget',
  'immersiveengineering:dust_steel',
  'mekanism:block_steel',
  'boss_tools:steel_block',
  
  'boss_tools:steel_sword',
  'boss_tools:steel_shovel',
  'boss_tools:steel_pickaxe',
  'boss_tools:steel_axe',
  'boss_tools:steel_hoe',
  'immersiveengineering:sword_steel',
  'immersiveengineering:shovel_steel',
  'immersiveengineering:pickaxe_steel',
  'immersiveengineering:axe_steel',
  'immersiveengineering:hoe_steel',
  'immersiveengineering:armor_steel_head',
  'immersiveengineering:armor_steel_chest',
  'immersiveengineering:armor_steel_legs',
  'immersiveengineering:armor_steel_feet',
  
  'industrialforegoing:infinity_trident',
  'industrialforegoing:infinity_drill',
  'industrialforegoing:infinity_launcher',
  'industrialforegoing:infinity_nuke',
  'industrialforegoing:infinity_saw',
  'industrialforegoing:infinity_backpack',
  'industrialforegoing:infinity_hammer',
  
   'minecraft:wooden_sword', 'minecraft:wooden_pickaxe', 'minecraft:wooden_shovel', 'minecraft:wooden_axe',
   'minecraft:stone_sword', 'minecraft:stone_pickaxe', 'minecraft:stone_shovel', 'minecraft:stone_axe', 'minecraft:stone_hoe',
   'minecraft:golden_pickaxe', 'minecraft:golden_axe',
   'minecraft:diamond_sword',
   'minecraft:netherite_pickaxe', 'minecraft:netherite_axe',
   'appliedenergistics2:certus_quartz_sword', 'appliedenergistics2:certus_quartz_pickaxe', 'appliedenergistics2:certus_quartz_shovel', 'appliedenergistics2:certus_quartz_axe', 'appliedenergistics2:certus_quartz_hoe',
   'appliedenergistics2:nether_quartz_sword', 'appliedenergistics2:nether_quartz_pickaxe', 'appliedenergistics2:nether_quartz_shovel', 'appliedenergistics2:nether_quartz_axe', 'appliedenergistics2:nether_quartz_hoe',
   'aquaculture:neptunium_sword', 'aquaculture:neptunium_axe',
   'atum:limestone_pickaxe', 'atum:limestone_sword', 'atum:limestone_axe', 'atum:stoneguard_sword', 'atum:stoneguard_greatsword',
   'aquaculture:neptunium_pickaxe',
   'minecraft:stone_axe', 'minecraft:golden_axe', 'minecraft:netherite_axe', 'atum:limestone_axe', 'aquaculture:neptunium_axe', 'minecraft:wooden_sword',
   'minecraft:stone_shovel', 'minecraft:golden_shovel', 'minecraft:netherite_shovel', 'appliedenergistics2:certus_quartz_shovel',
   'appliedenergistics2:nether_quartz_shovel',
   'aquaculture:neptunium_shovel',
   'atum:limestone_shovel',
   'betterendforge:aeternium_shovel',
   'betterendforge:thallasium_shovel',
   'betterendforge:terminite_shovel',
   'byg:pendorite_shovel',
   'endrem:end_crystal_shovel',
   'minecraft:wooden_hoe', 'minecraft:stone_hoe', 'minecraft:golden_hoe', 'minecraft:diamond_hoe', 'minecraft:netherite_hoe', 'endrem:end_crystal_hoe', 'byg:pendorite_hoe', 'betterendforge:aeternium_hoe', 'betterendforge:thallasium_hoe', 'betterendforge:terminite_hoe',
   'aquaculture:neptunium_hoe', 'atum:limestone_hoe', 'minecraft:golden_sword',
   'betterendforge:iron_hammer', 'betterendforge:golden_hammer',
   'luphieclutteredmod:luphie_general_store_cabinet', 'luphieclutteredmod:luphie_worn_dorado_cabinet',
   
   'notreepunching:clay_brick',
   'notreepunching:fire_starter',
   'charcoal_pit:fire_starter',
   'minecraft:wooden_hoe',
   
   'create:powdered_obsidian'
]

onEvent('jei.hide.items', event => {
  HIDDEN.forEach(item => event.hide(item))
})
